#!/bin/bash

./site rebuild

if [[ "$1" = "live" ]]
then
    rsync -r --delete --progress _site/* luke@leda:/var/www/lerlacher.de/
fi
rsync -r --delete --progress _site/* luke@leda:/var/www/area51.lerlacher.de/
